<?php namespace App\Modules\Rental\Models;

use App\Modules\Abstracts\Models\BaseModel;

class Address extends BaseModel
{
	public function __toString()
    {
        return parent::__toString(); // TODO: Change the autogenerated stub

    }
}